### ISSUE TITLE
Nombre del objeto

### ISSUE THREAD

**Issue by dahianagb07** [biogeografia-201902/unidad-0-asignacion-3-mi-primer-rmd-dahianagb07#1]
@geofis en la línea  #Por delante del símbolo de almohadilla, escribe el nombre del objeto
```¿Cómo consigo el nombre del objeto que me pide?

**Comment by geofis** [comment]
Si te refieres a qué debes poner en ese lugar (no me queda claro cuál es la pregunta o *issue*), significa que delante de la almohadilla, o sea, a su izquierda, debes colocar el nombre del objeto que debiste haber cargado [la línea anterior](https://github.com/biogeografia-201902/unidad-0-asignacion-3-mi-primer-rmd-dahianagb07/blob/f6b21b3e89b42606c3f158c486a2fa8d246573cd/README.Rmd#L99)

**Comment by dahianagb07** [comment]
Cargue las líneas anteriores (tanto la matriz mite como vegan) y no salen las columnas de números y nombres que debería de salir. Tengo el mismo problema que en el día en clases🙁

**Comment by geofis** [comment]
¿Podrías poner una captura de pantalla de lo que haces (sea en la pestaña del `.Rmd` o en la consola), así como el mensaje de error (si lo hubiere)?

**Comment by geofis** [comment]
Prueba ahora @dahianagb07. Clona tu repo de nuevo, haz lo que se te pide y verifica si obtienes resultados.

**Comment by geofis** [comment]
Supongo @dahianagb07 que puedo cerrar este *issue*, porque ya está resuelta la cuestión planteada.
